# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordinate_descent_update <- function(X, y, beta, w, r, lambda, active_set) {
    .Call('_heavylasso_coordinate_descent_update', PACKAGE = 'heavylasso', X, y, beta, w, r, lambda, active_set)
}

